In [8]:
import duckdb
import pandas as pd
from nyc_taxi.config.settings import DATABASE_PATH

# Connect to a file-based database (or ':memory:' for temporary)
con = duckdb.connect(DATABASE_PATH)

# Execute query and convert to pandas
yellow = con.sql("SELECT * FROM raw_taxi.yellow_taxi").df()

yellow.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,1,2025-01-01 00:18:38,2025-01-01 00:26:59,1,1.60,1,N,229,237,1,10.0,3.5,0.5,3.00,0.0,1.0,18.00,2.5,0.0,0.0
1,1,2025-01-01 00:32:40,2025-01-01 00:35:13,1,0.50,1,N,236,237,1,5.1,3.5,0.5,2.02,0.0,1.0,12.12,2.5,0.0,0.0
2,1,2025-01-01 00:44:04,2025-01-01 00:46:01,1,0.60,1,N,141,141,1,5.1,3.5,0.5,2.00,0.0,1.0,12.10,2.5,0.0,0.0
3,2,2025-01-01 00:14:27,2025-01-01 00:20:01,3,0.52,1,N,244,244,2,7.2,1.0,0.5,0.00,0.0,1.0,9.70,0.0,0.0,0.0
4,2,2025-01-01 00:21:34,2025-01-01 00:25:06,3,0.66,1,N,244,116,2,5.8,1.0,0.5,0.00,0.0,1.0,8.30,0.0,0.0,0.0

In [9]:
yellow.shape

(15168579, 20)

In [7]:
green = con.sql("SELECT * FROM raw_taxi.green_taxi").df()

CatalogException: Catalog Error: Table with name green_taxi does not exist!
Did you mean "yellow_taxi"?

In [ ]:
green.shape

(1463, 19)

In [ ]:
green.head()

,vendorid,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,ratecodeid,pulocationid,dolocationid,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2,2023-01-01T00:01:31.000,2023-01-01T00:16:02.000,N,1.0,166,244,1.0,2.48,16.3,1.0,0.5,3.76,0.0,1.0,22.56,1.0,1.0,0.0
1,2,2023-01-01T00:04:25.000,2023-01-01T00:17:50.000,N,1.0,255,146,1.0,2.8,16.3,1.0,0.5,2.8,0.0,1.0,21.6,1.0,1.0,0.0
2,2,2023-01-01T00:06:48.000,2023-01-01T01:08:47.000,N,1.0,129,226,2.0,7.83,52.0,1.0,0.5,0.0,0.0,1.0,54.5,2.0,1.0,0.0
3,2,2023-01-01T00:08:05.000,2023-01-01T00:13:26.000,N,1.0,41,75,6.0,1.05,5.5,0.5,0.5,1.36,0.0,0.3,8.16,1.0,1.0,0.0
4,2,2023-01-01T00:08:43.000,2023-01-01T00:17:08.000,N,1.0,75,140,1.0,1.99,11.4,1.0,0.5,3.33,0.0,1.0,19.98,1.0,1.0,2.75

In [7]:
green.tail()

,vendorid,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,ratecodeid,pulocationid,dolocationid,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
1458,2,2023-01-01T23:44:20.000,2023-01-02T00:20:24.000,N,1.0,255,50,3.0,7.43,38.0,1.0,0.5,0.0,0.0,1.0,43.25,2.0,1.0,2.75
1459,2,2023-01-01T23:47:07.000,2023-01-01T23:57:07.000,N,5.0,260,260,0.0,2.79,15.0,0.0,0.0,3.2,0.0,1.0,19.2,1.0,2.0,0.0
1460,2,2023-01-01T23:53:24.000,2023-01-02T00:05:41.000,N,1.0,17,80,5.0,2.57,14.9,1.0,0.5,3.48,0.0,1.0,20.88,1.0,1.0,0.0
1461,2,2023-01-01T23:53:37.000,2023-01-02T00:21:56.000,N,1.0,223,50,1.0,5.92,30.3,1.0,0.5,5.0,0.0,1.0,40.55,1.0,1.0,2.75
1462,2,2023-01-01T23:55:51.000,2023-01-02T00:03:41.000,N,1.0,74,75,1.0,2.17,12.1,1.0,0.5,2.92,0.0,1.0,17.52,1.0,1.0,0.0

In [1]:
import pyarrow
print(pyarrow.__version__)

23.0.1

In [2]:
import duckdb
print(duckdb.__version__)

1.5.1